### ISSUE TITLE
mas resultas!!!

### ISSUE THREAD

**Issue by MMAKENPO** [alexbcberio/itunes-artwork-finder#1]
hola hermano!!!increibleeeeeeeeeeeee pagina...muchas felicidades Alex....pero por favor puedes hacerlo aparecio ilimitadas resultas?hermano me encanta musica espanol y especial pop balada...cuanto que no imagines!!!lo se que itunes tiene maxima 200 resultas pero estoy muy seguro como development que eres puedes hacer aparecio ilimitadas resultas por cada cancion y album!!!te lo ruegoooooooooooooooooooooo manito!!!abrazos y Dios que te cuide!!!

**Comment by alexbcberio** [comment]
[EN]
I've looked up the iTunes API and unfortunatelly it does not support more than 200 results nor pagination of responses. So multiple requests made with the same input return the same items.

The current implementation does not change the default result limit of 50 items, I'll set up a box to specify the maximun number of results up to 200 items.

I'm sorry but I cannot do any more.

Thanks for your appreciattion. ❤️ 

---
[ES]
He revisado la API de iTunes para ver si puede ser implementado lo que mencionas, desafortunadamente la API no soporta paginar los resultados. Por tanto múltiples envíos de la misma petición dan un mismo resultado.

La implementación actual no cambia el número de resultados máximos, 50 items. Voy a añadir un campo para poder cambiar dicho número hasta a 200.

No puedo hacer nada más dado que no está a mi alcance.

Muchas gracias por tu agradecimiento. ❤️

**Comment by MMAKENPO** [comment]
hola amigo!!!gracias por tu contesta!!!pero hermano debe que hay algun manera aparecio ilimitadas resultas!!!cheque por favor!!!

**Comment by alexbcberio** [comment]
Maximun number of results can now be specified manually in commit [a5daeb7](https://github.com/alexbcberio/itunes-artwork-finder/tree/a5daeb766824491a018c9dd97320b9ff68350d25)

Closing the issue since I cannot do anything more. Feel free to reopen if you find any bugs

---
Número máximo de resultados puede ser expecificado manualmente tras commit [a5daeb7](https://github.com/alexbcberio/itunes-artwork-finder/tree/a5daeb766824491a018c9dd97320b9ff68350d25)

Cierro el "issue" dado que no puedo hacer nada mas. Reabre en caso de encontrarte con cualquier bug/error.

**Comment by alexbcberio** [comment]
> hola amigo!!!gracias por tu contesta!!!pero hermano debe que hay algun manera aparecio ilimitadas resultas!!!cheque por favor!!!

He estado mirando la documentación y haciendo pruebas y no he encontrado ninguna forma para implementar resultados ilimitados.
No hay nada mas que pueda hacer desgraciadamente

**Comment by MMAKENPO** [comment]
hermano es que me encanta musicaaaaaaaaaaaaaa espanol muchisimoooooooooooo...por eso mi paciensia!!!pero no puedes hacer un button colo load more?eres development...si?creo que puedes hacer un button load more amigo!!!te lo ruego hermano!!!

**Comment by MMAKENPO** [comment]
amigo me fascina tu pagina...muy buen design and las caratulas son muy claras!!!hermanito cheque esa pagina por favor!!!sale ilimitadas resultas pero no me gusta.....tuya es mucho mejor que esa!!!por eso estoy muy seguo que puedes aparecio ilimitadas resultas!!!  https://music.zacharyseguin.ca/us/search?q=eres&type=songs

**Comment by alexbcberio** [comment]
> amigo me fascina tu pagina...muy buen design and las caratulas son muy claras!!!hermanito cheque esa pagina por favor!!!sale ilimitadas resultas pero no me gusta.....tuya es mucho mejor que esa!!!por eso estoy muy seguo que puedes aparecio ilimitadas resultas!!! https://music.zacharyseguin.ca/us/search?q=eres&type=songs

Desconocia esta otra api de iTunes, si puede ser utilizada sin requerir ningún tipo de autenticación migraré todo a esta.

Esto será una tarea mas larga, iré informando del estado por medio de la issue.

¡¡¡Muchas gracias por el aporte!!!

**Comment by MMAKENPO** [comment]
woowwwwwwwwwwwww....entonces tal vez puedes aparecio tu increible pagina ilimitadas resultas hermano?

**Comment by MMAKENPO** [comment]
woowwwwwwwwwwwww....entonces tal vez puedes aparecio tu increible pagina ilimitadas resultas hermano?

**Comment by alexbcberio** [comment]
> woowwwwwwwwwwwww....entonces tal vez puedes aparecio tu increible pagina ilimitadas resultas hermano?

Asi es, me va llevar tiempo dado que voy a organizar mejor el provecto. Ten un poco de paciencia

**Comment by MMAKENPO** [comment]
wowwwwwwwwwwwwwwwwwww hermano.......hablas en serio???ay Dios mio muchisisisisisisisisimas graciasssssssss manito...que buenas noticias...hermano soy Griego pero no se que paso conmigo...me fascinaaaaaaaaaaaaaaaaaa musica espanol y especial pop balada!!!te agradezco mucho hermano si lo haces!!!dime tienes facebook?quiero te envio solicitud!!!

**Comment by MMAKENPO** [comment]
hermano y por favor un favor mas amigo...tal vez puedes hacer una busqueda por fecha y por generos?seria muyyyyyyyyyyyyyyyyyyyyy increible y esas futuros hacer tu pagina irresistible!!!estoy segurisimo amigo!!!pero solo si puedes y quieres claro!!!si no?a menos por favor hacer aparecio ilimitadas resultas!!!un abrazo desde Grecia y Dios que cuide usted y tu familia!!! 

este es mi facebook...me gustaria me mandas solicitud!!!cuidate hermano y muchas gracias antemano!!! https://www.facebook.com/panos.papadopulos

**Comment by alexbcberio** [comment]
> hermano y por favor un favor mas amigo...tal vez puedes hacer una busqueda por fecha y por generos?seria muyyyyyyyyyyyyyyyyyyyyy increible y esas futuros hacer tu pagina irresistible!!!estoy segurisimo amigo!!!pero solo si puedes y quieres claro!!!si no?a menos por favor hacer aparecio ilimitadas resultas!!!un abrazo desde Grecia y Dios que cuide usted y tu familia!!!
> 
> este es mi facebook...me gustaria me mandas solicitud!!!cuidate hermano y muchas gracias antemano!!! https://www.facebook.com/panos.papadopulos

Sorry, no tengo facebook (edito tu mensaje para eliminar la url por seguridad). Tengo otras redes sociales (mandame mensaje privado y te indico por ahí)

Abre un nuevo issue para la implementación de la búsqueda avanzada (fecha y género) para tener casa cosa separada y poderlo gestionar más fácilmente.

**Comment by MMAKENPO** [comment]
aaaaaaaaa...que pena que no usas facebook!!!ok manito!!!voy a borrarlo...correo tampoco?

**Comment by alexbcberio** [comment]
Siento defraudarte pero no puedo hacer el scroll infinito, debido a que necesito tener un dispositivo de Apple para poder activar la autenticación de doble factor (2FA) y darme de alta como desarrollador de Apple (https://support.apple.com/en-us/HT204915).

He intentado buscar otras opciones pero desgraciadamente no he encontrado nada.
