### ISSUE TITLE
busqueda por generos y fecha!!!

### ISSUE THREAD

**Issue by MMAKENPO** [alexbcberio/itunes-artwork-finder#2]
..tal vez puedes hacer una busqueda por fecha y por generos?seria muyyyyyyyyyyyyyyyyyyyyy increible y esas futuros hacer tu pagina irresistible!!!estoy segurisimo amigo!!!pero solo si puedes y quieres claro!!!si no?a menos por favor hacer aparecio ilimitadas resultas!!!un abrazo desde Grecia y Dios que cuide usted y tu familia!!!

cuidate hermano y muchas gracias antemano!!!

**Comment by MMAKENPO** [comment]
hermano crees que hasta el fin de semana podria sera listo???tengo muchas ganas buscar todas la canciones pop balada con titulo eres,dejame,perdoname,amor,vulelve,estoy y mucho massssssssss!!!!abrazos desde Grecia hermano.

**Comment by alexbcberio** [comment]
Una vez terminado con el issue 1 me pondre a ver esta, hasta entonces no te se decir fechas.

**Comment by MMAKENPO** [comment]
hola hermano!!!Alex como puedo comunicar contigo en privado?ayudame amigo por favor

**Comment by MMAKENPO** [comment]
Alex crees que va tardara mucho hermanito?
