### ISSUE TITLE
unlimited results!!!

### ISSUE THREAD

**Issue by MMAKENPO** [alexbcberio/itunes-artwork-finder#3]
my good friend nothing yet about unlimited results!!!pleaseeeeeeeeee man

**Comment by alexbcberio** [comment]
I'm so sorry but in ordee to develop that apple requires me to own an apple
device in order to activate 2FA. Once 2FA is enabled I could create a
developer key and get all the data.
I've been plenty of time searching an alternative and I found nothing.

Really sorry :'(

**Comment by MMAKENPO** [comment]
ooooooooooooo really my friend?>>there is no another way to increase unlimited???

**Comment by MMAKENPO** [comment]
but your web is muchhhhhhhhhhhhhhhhhhhhhh betterrrrrrrrrrrrrrrr than these 2 webs where I send you!!!pleaseeeeeeeeeeeeeeee Alex try it my friend!!!!!!!!!!!!I AM BEGGING YOUUUUUUUUUUUUUUUUU

**Comment by MMAKENPO** [comment]
ALEX MY GOOD FRIEND I KNOW THAT ITUNES HAVE LIMIT 200-300 RESULTS BUT WITH SOME WAY YOU CAN INCREASE UNLIMITED!!!I LOVE SO MUCH SPANISH MUSIC ESPECIALLY POP BALADA...I AM BEGGING YOUUUUUUUUUUUUUUU COULD YOU INCREASE UNLIMITED RESULTS?IT WOULD BE GREAT!!!I HAVE NO IDEA FROM DEVELOPING AND ONE PERSON WHERE WE TALKING FROM FACEBOOK WANTS 400 EURO AT LEAST TO MAKE ME ONE WEB WHERE USE API FROM ITUNES!!!AND I HAVE NOT THESE MONEY TO DO IT!!!!GOD BLESS YOU!!!! THIS WEB SHOWS UNLIMITED BUT I DONT LIKE BECAUSE SHOWS MANYYYYYYYYYYY DUPLICATE RESULTS UNFORTUNATELY!!!!!!!!!!!!!!! https://rnosov.github.io/ItunesSearch/

**Comment by alexbcberio** [comment]
As I previously told you I cannot enroll as a developer into Apple platform as I don't met the first requirement (enable two factor authentication using an apple device).

You can find the requirements in the following page: https://developer.apple.com/programs/enroll/

And here is the screenshot of the page of me trying to enroll, you can see in the image that I have enabled two-step verification (I get an SMS on the phone every time I log in) but I require two factor authentication.

![apple developer enrollment requirements](https://user-images.githubusercontent.com/22194879/76403172-cd55b300-6384-11ea-86f1-228379f484fe.png)

The page you sent me uses the same API I'm currently using, he uses a parameter that is not specified at the documentation and seems to work. I can try to implement it but I could get duplicate elements as he is getting.

**Comment by MMAKENPO** [comment]
OOOOOOOOOOOOOOO ALEX MY FRIEND THERE IS AND THIS WEB ALSO!!!MAN  TRY WITH THIS PLEASEEEEEEEEEEE https://music.zacharyseguin.ca/us/search?q=TU&type=albums

**Comment by MMAKENPO** [comment]
DUPLICATE ELEMENTS ITS VERY BAD?

**Comment by alexbcberio** [comment]
You sent me this site earlier and this one uses the API that needs authentication.

The thing of duplicate elements is that is not visually appealing

**Comment by MMAKENPO** [comment]
AAAA OK MAN!!!!I HAVE NO OTHER!!!!ALEX MY FRIEND IF THERE IS NO OTHER WAY MAKE IT WITH SOME DULPICATE SONGS!!!I AM BEGGING YOU DUDEEEEEEEEEEE....BUT ITS UP TO YOU AND ONLY!!!

**Comment by MMAKENPO** [comment]
Judging by the code that I found on the github, unlimited search
works if you set the limit to 10 and set the offset in the query parameters
when scrolling for the data received.

**Comment by MMAKENPO** [comment]
pleaseeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeemy good friend Alexxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!

**Comment by MMAKENPO** [comment]
Alex my friend could you make one web with unlimited results and some duplicate only for me?you will make me so happyyyyyyyyyyyyyyyyyyyyyyy my friend!!!!

**Comment by alexbcberio** [comment]
I've implemented it but it shows a lot of duplicate elements. It's not worth the deployment.
I'm not going to invest more time into it as it's not viable.

Please don't insist any more.

**Comment by MMAKENPO** [comment]
ok my good frienddddddddddddd....you right!!!I dont want make you angry with me!!!!is where I love so much spanish music,and I d like to find all the results!!!but you decide Alex!!!I find also this!!!but yours is much better!!! http://itunes-search.romanpaprotsky.com/

**Comment by MMAKENPO** [comment]
i dont remember if i send you and this web!!!just these  3 webs I know!!!

**Comment by alexbcberio** [comment]
I'm closing the issue as there's nothing else I can do.

**Comment by MMAKENPO** [comment]
yes,I understand...and please sorry for my paciense!!!Dios que te guarde amigo y mil gracias por tu tiempo!!!
