### ISSUE TITLE
fecha!!!

### ISSUE THREAD

**Issue by KENPOKASMMA1982** [alexbcberio/itunes-artwork-finder#30]
Alex saludos desde Grecia amigo!te lo ruegooooooooooooo funciona buscar por fecha ano y mes amigo!seria increibleeeeeeeeeeee!!!gracias de antemano!!

**Comment by alexbcberio** [comment]
Hace tiempo empecé a rehacer la web de cero para añadir varias funcionalidades extras, desafortunadamente no tengo tiempo para invertir en todos los proyectos y tengo que priorizarlos.

Esta web es de los proyectos menos importantes y por ahora solo voy a mantenerlo actualizando dependencias por problemas de seguridad.

Siendo realistas, es poco probable que continue y añada estas funcionalidades
